### PR TITLE
GramBank -> Grambank

### PR DESCRIPTION
**Pull request by HedvigS**
Is this the right way to go about this?

### CODE REVIEW

**Comment by HedvigS** [comment]
I'd also add some explained of how the coverage table works, but I don't know where one would do that.

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
You can add some info as HTML here: https://github.com/HedvigS/grambank/blob/182345aca082a3bdc95fb52540297dfaf9ab1b33/grambank/templates/coverage.mako#L4

**Comment by HedvigS** [comment]
@xrotwang Okay, thanks. I'll see if I can do that smoothly.

What is a "subunit" here?

**Comment by HedvigS** [comment]
and... what is the Family "100%"?

**Comment by xrotwang** [comment]
Subunits are the next taxonomic groups under the top-level unit. And I believe 100% coverage for a family means all of its subunits have been sampled.

**Comment by HedvigS** [comment]
Okay. Is there any more precise information on how these subunits were defined? There could be less or more subunits for several of the families depending on choices.

I understand that if a family has 100% coverage that means all subunits are sampled. But what is the Family with the name "100%"? :)

Likewise, the subunit with the name "0%" etc.

Screenshot 2021-04-26 at 14 16 57

**Comment by xrotwang** [comment]
That isn't really well-maintained code. Maybe we should just remove this page, than figuring out what https://github.com/clld/grambank/blob/master/grambank/scripts/coverage.py does.

**Comment by HedvigS** [comment]
About subunits, to make it clearer. Why isn't "Atayalic" a subunit under Austronesian in the table for example? It can't just be the immediate daughter branches of the root. There's something else going on :)

**Comment by HedvigS** [comment]
Yeah maybe. I like the idea, I'd just want to complete it a bit more and add text to explain things if it's there.

**Comment by xrotwang** [comment]
If we find it difficult to figure out what exactly this page shows, it probably won't be very informative for others - other than it's mostly green, so probably good.

**Comment by xrotwang** [comment]
I'm for removing. The page was only meant to inform internal project coordination anyway. Whether the coverage of Grambank is suitable for any particular research questions wouldn't have been answered with this page anyway.

**Pull request merged**
