### PR TITLE
Link feature to families

### PR DESCRIPTION
**Pull request by johenglisch**
* Added box to feature page that lets you choose a language family (cf. #12).
 * Adapted the family page so it uses the same code.
 * Filtered the list, so the box only shows family--feature combinations that
   actually exist (example of a non-existing combination:
   https://grambank.clld.org/familys/kres1240?feature=GB432#0/0/0)

family-chooser

### CODE REVIEW

**Comment by HedvigS** [comment]
I think Simon should review

**Review by xrotwang — APPROVED** [review]
Putting together a sqlalchemy ORM query in python code may be somewhat more elegant (in particular since this would take care of the joined inheritance automatically), but then, shuffling results back and forth between view and backend would add bloat as well.
So I think this is fine as is.

**Comment by johenglisch** [comment]
>I think Simon should review

I think right now it might be best to just merge this and push it to the webapp.  Then everybody can look at it on the running site, click all the things, and see if there are problems/suggestions/etc.

**Comment by xrotwang** [comment]
> I think right now it might be best to just merge this and push it to the webapp.

Please wait with deploying changes to the web app until the current status is reviewed and ok-ed by project lead.

**Comment by johenglisch** [comment]
Got it

**Comment by johenglisch** [comment]
Seems like this PR got lost in the shuffle during release.  Do we want to merge it now?

**Comment by HedvigS** [comment]
> Seems like this PR got lost in the shuffle during release. Do we want to merge it now?

I think so, but I don't know who we're waiting for here.

**Comment by HedvigS** [comment]
If we want Simon to review, someone needs to add him to the repos.

**Comment by SimonGreenhill** [comment]
I'm not sure what to review here -- the code all looks sensible to me but I'd need to see it on the webpage. Can we merge and deploy and then refine if needed?

**Comment by johenglisch** [comment]
Okay, I redeployed (which also includes the changes made to address #74).  If you wanna have a look, here's some links to the changed pages:

You can choose a feature at the top of the family page (I think that worked before the PR); e.g. Arawakan:

    https://grambank.clld.org/familys/araw1281

You can choose a language family on the feature page, above the map, right where the *Combine Two Features with Each Other* button is as well; e.g. GB074:

    https://grambank.clld.org/parameters/GB074#2/21.0/152.1

And here's the combination page of Arawakan+GB074:

    https://grambank.clld.org/familys/araw1281?feature=GB074

**Comment by HedvigS** [comment]
> https://grambank.clld.org/familys/araw1281

@SimonGreenhill Is this to your satisfaction?

**Comment by SimonGreenhill** [comment]
thanks @johenglisch -- looks good. Is there any chance to have the map and the phylogeny side by side ? (e.g. a div with 80% map, 20% tree)

**Pull request merged**
