### PR TITLE
remove blurbs and photos from conributors page to avoid data getting …

### PR DESCRIPTION
**Pull request by xrotwang**
…out-of-sync

Note: I already applied these changes on the server, to let the project lead have a look.

### CODE REVIEW

**Comment by johenglisch** [comment]
I'm unsure how well

    cc.name.split()[-1]

works for getting the last name.  We have a few names that look like there might be more than one last name (at least to my dumb Central European eyes).

But at the same time splitting names is one of those things that is impossible to automate to begin with… (iirc CONTRIBUTORS.md in the data repo has them split up manually).

**Comment by xrotwang** [comment]
I'd say "good enough" in this case.

**Review by johenglisch — APPROVED** [review]

**Comment by HedvigS** [comment]
We already have last name and first name categories in glottobank/grambank contributors.md. Why do we need a new way of pulling out last names?

**Comment by xrotwang** [comment]
This is only for alphabetic sorting.

**Comment by HedvigS** [comment]
> This is only for alphabetic sorting.

Okay. For the author list for the paper I split names like "van der Meer" into "van der" and "Meer" and sorted by the second part. Do you want me to help do something similar here?

**Comment by xrotwang** [comment]
> Okay. For the author list for the paper I split names like "van der Meer" into "van der" and "Meer" and sorted by the second part. Do you want me to help do something similar here?

Incidentally, that's what the quick-and-dirty `name.split()[-1]` does. So I'd just leave it at that. Alternatively, one could use `nameparser`:
```python
>>> from nameparser import HumanName
>>> n = HumanName('Hans van der Meer')
>>> n
<HumanName : [
	title: '' 
	first: 'Hans' 
	middle: '' 
	last: 'van der Meer' 
	suffix: ''
	nickname: ''
]>
```

**Comment by HedvigS** [comment]
> > Okay. For the author list for the paper I split names like "van der Meer" into "van der" and "Meer" and sorted by the second part. Do you want me to help do something similar here?
> 
> Incidentally, that's what the quick-and-dirty `name.split()[-1]` does. So I'd just leave it at that. Alternatively, one could use `nameparser`:
> 
> ```python
> >>> from nameparser import HumanName
> >>> n = HumanName('Hans van der Meer')
> >>> n
> <HumanName : [
> 	title: '' 
> 	first: 'Hans' 
> 	middle: '' 
> 	last: 'van der Meer' 
> 	suffix: ''
> 	nickname: ''
> ]>
> ```

Right, but for "Roberto E. Herrera Miranda" it'd think that the last name is "Miranda" right?

**Pull request merged**
